import LandingPage from "@/src/components/Home";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Nepal Health</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LandingPage />
      </div>
    </>
  );
}
